<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-ListenBucket-41983549-faab-4291-b3bc-7c65ff84bc78</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BlazorStrap.Extensions.FluentValidation" Version="2.0.1" />
        <PackageReference Include="BlazorStrap.V5" Version="5.2.104" />
        <PackageReference Include="FFMpegCore" Version="5.2.0" />
        <PackageReference Include="Google.Apis.YouTube.v3" Version="1.70.0.3847" />
        <PackageReference Include="Hangfire.AspNetCore" Version="1.8.21" />
        <PackageReference Include="Hangfire.Core" Version="1.8.21" />
        <PackageReference Include="Hangfire.Storage.SQLite" Version="0.4.2" />
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.9" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="System.ServiceModel.Syndication" Version="9.0.9" />
        <PackageReference Include="YoutubeDLSharp" Version="1.1.2" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ListenBucket.ServiceDefaults\ListenBucket.ServiceDefaults.csproj" />
    </ItemGroup>

</Project>
